# Generated by Django 4.1.2 on 2022-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="album_ID",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="dom_colour",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
