# Generated by Django 4.1.2 on 2022-10-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_photo_album_id_photo_dom_colour_photo_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="album_ID",
            field=models.IntegerField(default=1),
        ),
    ]
