# Generated by Django 4.1.2 on 2022-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_photo_dom_colour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="album_ID",
            new_name="albumId",
        ),
        migrations.AddField(
            model_name="photo",
            name="url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
