# Generated by Django 4.1.2 on 2022-10-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_remove_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
