# Generated by Django 4.1.2 on 2022-10-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_photo_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="albumId",
            new_name="albumid",
        ),
    ]
